--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/reyyan987/VoidCore
build-by-default: true
branches:
- main
projects:
  VoidCore:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2

...
