---
name: voidpvp
version: 0.0.1
main: voidpvp\ffamap\Main
api: 4.0.0
author: Voidpvp
src-namespace-prefix: voidpvp\ffamap
depend:
 - ProperDuels
commands:
    ffamap:
        description: hehe dont come
        permission: ffamap.ui
    dmap:
        description: hehe dont come
        permission: dmap.ui
    gladiator1:
        description: gladiator only come here
        permission: g.ui
    kungfu1:
        description: kungfu only come here
        permission: k.ui
    city1:
        description: city only come here
        permission: c.ui
    dselector:
        description: dselector only come here
        permission: d.ui
permissions:
    ffamap.ui:
        default: true
    dmap.ui:
        default: true
    k.ui:
        default: true
    c.ui:
        default: true
    g.ui:
        default: true
    d.ui:
        default: true
... 
